
# version format
version: 0.1.5.{build}

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: sdk\solutions\WinSDK4Desktop\WinSDK4Desktop.sln      # path to Visual Studio solution or project

before_build:
  - ps: nuget restore sdk\solutions\WinSDK4Desktop\WinSDK4Desktop.sln
  
test:
   assemblies:
    except:
     - SparkSDKTests.dll
# deploy:
  # - provider: GitHub
    # on:
      # branch: master                # release from master branch only
notifications:
# Email
  - provider: Email
    to:
      zhang.shangwu@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true     